default: &default
  adapter: postgresql
  encoding: unicode
  username: playtape
  password: camus
  pool: 5

development:
  <<: *default
  database: playtape_dev

test:
  <<: *default
  database: playtape_test

production:
  <<: *default
  database: playtape_production
